### ISSUE TITLE
Vim-css-color not working outside of comments

### ISSUE THREAD

**Issue by atoms-who-code** [ap/vim-css-color#107]
![screenshot-2019-01-02-20 20 26](https://user-images.githubusercontent.com/40503781/50621499-e08d0900-0ecb-11e9-9aab-ec6b72a09f4f.png)

**Comment by ap** [comment]
…?

**Comment by taigrr** [comment]
Whoa. Ok, this plugin wasn't working at all for me, but adding a comment made all the colors highlight as expected. I can second this bug. 

What info can I provide you to help me debug @ap ?
