### ISSUE TITLE
Support for othree/yajs.vim

### ISSUE THREAD

**Issue by ap** [ap/vim-css-color#113]
```vim
Plug 'ap/vim-css-color', { 'for': ['javascript.jsx', 'html', 'htmldjango'] }
```

![](https://i.imgur.com/3x7xz6L.png)

_Originally posted by @Fandekasp in https://github.com/ap/vim-css-color/issues/89#issuecomment-500723793_

**Comment by ap** [comment]
@Fandekasp: If you move the cursor into a string that should be highlighted but isn’t and issue the following command, what does it say?
````vim
:echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
````

**Comment by Fandekasp** [comment]
@ap thanks for the quick follow-up :heart: 

Line not highlighted:
```
      teal: "#00aed7", //{

['javascriptObjectLiteral', 'javascriptObjectLiteral', 'javascriptObjectLiteral', 'javascriptString']
```

Line highlighted:
```
        //100: "#e6fffa", 

['javascriptObjectLiteral', 'javascriptObjectLiteral', 'javascriptObjectLiteral', 'javascriptLineComment', 'BGe6fffa']
```

**Comment by ap** [comment]
The JS(X) syntax plugin you are using is not yet supported, only the Vim stock Javascript syntax and and [pangloss/vim-javascript](/pangloss/vim-javascript).

You get colours in comments anyway because group names are not case sensitive and the Vim stock Javascript syntax uses `javaScriptLineComment` – which happens to match `javascriptLineComment` case insensitively.

But the stock syntax has only `javaScriptStringS` and `javaScriptStringD` and nothing that would match `javascriptString`, so that case goes uncovered.

(And pangloss’ syntax uses `js` as its group name prefix, so it doesn‘t come up here at all.)

What plugin are you using?

**Comment by Fandekasp** [comment]
@ap  I see. Here are the plugins I use for js.
```
Plug 'othree/yajs.vim', { 'for': 'javascript' }                               
Plug 'mxw/vim-jsx', { 'for': 'javascript' } 
```

**Comment by ap** [comment]
There you go. Share and enjoy 🙂

**Comment by ap** [comment]
Whoops.

**Comment by Fandekasp** [comment]
Many thanks @ap!
