### ISSUE TITLE
no functionality for c or header files

### ISSUE THREAD

**Issue by ThePaulODoom** [ap/vim-css-color#120]

**Comment by KunaPrime** [comment]
@ThePaulODoom  please could you test  #121

**Comment by ap** [comment]
There is some support for C… so the question is what did you expect to be highlighted that wasn’t?

**Comment by ap** [comment]
Oh sorry. Joke’s on me… I never released the C support.

**Comment by ap** [comment]
There we go. Sorry about that. Share and enjoy 🙂
