### ISSUE TITLE
Not working with GVim

### ISSUE THREAD

**Issue by Leetovskiy** [ap/vim-css-color#123]
In console Vim plugin is working fine but in GVim it is absolutely don't work.
Code look in Vim:
![image](https://user-images.githubusercontent.com/22835084/80208947-b0b5c780-8620-11ea-906d-961fa6a19f55.png)
and the same in GVim:
![image](https://user-images.githubusercontent.com/22835084/80209063-e22e9300-8620-11ea-96b5-439c8a9606ff.png)

**Comment by ap** [comment]
When you run these commands in GVim, what do they say?
````vim
:set syntax?
:echo has('gui_running')
````

When you move the cursor onto a color definition (like `#d7373b` in your screenshot) and run this command, what does it say?
````vim
:echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
````

**Comment by Leetovskiy** [comment]
@ap whoops, I'm sorry. The cause of the problem is I opened old Vim session that isn't loads the plugin. Feel awkward :)
