### ISSUE TITLE
How to disable/enable?

### ISSUE THREAD

**Issue by eduardoarandah** [ap/vim-css-color#125]
In some filetypes, it doesn't make sense having this highlighting enabled. 

Is there a way of enabling/disabling? 
o based on filetype?

I'm thinking about enabling only for css

**Comment by ap** [comment]
There is currently no such feature. What filetypes do you find it unnecessary in?

**Comment by eduardoarandah** [comment]
Sometimes it's distracting in html, with color names (red, blue, white)

Also, it's weird to color names in a .txt file hehe, let's say you're taking notes about a company called "yellow submarine" 

I tried this, but I don't know why it doesn't have effect:

```
Plug 'ap/vim-css-color', { 'for': [ 'css', 'scss' ] }
```

https://github.com/junegunn/vim-plug#example

(right one is html)
![image](https://user-images.githubusercontent.com/4065733/82566331-5afe0d80-9b41-11ea-8b30-11ea49e790b2.png)

**Comment by ap** [comment]
Would you say your request has the same motivation as #124 then?

I am guessing the fact that this plugin relies on the `after` and `autoload` mechanisms of Vim is why you can’t disable it that way.

**Comment by eduardoarandah** [comment]
Yeah I guess. 

Without knowing how this plugin does its magic, can't it be registered only when a specific filetype opens? 

like `setlocal` instead of `set` or `autocmd BufReadAfter *.css` ? 

I have this in my vimrc to do some customization on specific filetypes:

```
augroup filetypes
  autocmd!

  " Blade filetype
  autocmd BufRead,BufNewFile *.blade.php set filetype=blade

  " Txt as markdown
  autocmd BufReadPost *.txt set filetype=markdown

augroup END

```

**Comment by ap** [comment]
It doesn’t work that way, so no. At least not without changing how it works. Now that I think about it, the way it works may just be historical baggage and not necessary, and changing it might solve other problems as well. I need to have a think on that.

**Comment by ap** [comment]
@at1047 just posted [a real solution for this](/ap/vim-css-color/issues/136#issuecomment-670853624) in #136, albeit one that requires modifying the plugin.

**Comment by Zeioth** [comment]
It would be nice to be able to enable it only on CSS files. I don't want my .md to highlight every time i write 'blue' or 'silver'.

**Comment by ap** [comment]
@Zeioth:

> I don't want my .md to highlight every time i write 'blue' or 'silver'.

I wouldn’t want that either. And so it doesn’t:
<img alt="" width="610" height="312" src="https://user-images.githubusercontent.com/1683/99922805-bb5d4a00-2d32-11eb-93b7-ba06521ceb7f.png">
It highlights `blue` or `silver` *only* when those are actually used in CSS when defining colours. That fact is literally the whole point of using this plugin over otherwise similar, comparable ones.

**Comment by eduardoarandah** [comment]
Here's a solution to not load this plugin in files other than CSS/SCSS

```
Plug 'ap/vim-css-color', { 'for': [ 'css', 'scss' ] }
```
