### ISSUE TITLE
Plugin not working at all

### ISSUE THREAD

**Issue by azizn03** [ap/vim-css-color#132]
Hi Everyone,

I am trying to get the following plugin to work using Vundle.

https://github.com/ap/vim-css-color

I have installed lightline without any issues, using the same setup I installed the previous plugin yet the colours are not showing up on the text files. Any suggestions?

Screenshot showing lightline working along with after running the :PluginInstall command.

https://imgur.com/a/o6prVPk

my .vimrc file.

https://imgur.com/a/NHKI9Ke

**Comment by jordelver** [comment]
It looks like lua is not currently supported https://github.com/ap/vim-css-color/tree/master/after/syntax

Maybe you could init it manually yourself or add support for lua using those examples as start?

**Comment by ap** [comment]
> It looks like lua is not currently supported

Correct. Specifically it’s no longer supported, and unfortunately it’s not likely to become supported again, not anytime soon. The stock Lua syntax would have to be completely rewritten first.

See also #65 and #70.

However you can use the old, buggy Lua support if you’re OK with the bugs. I’ve described how to do that in #70.

@azizn03: Does that answer all your questions?

**Comment by azizn03** [comment]
It does, my mistake that should have been something I noticed.

**Comment by ap** [comment]
No worries. 🙂
