### ISSUE TITLE
add support for lua files?

### ISSUE THREAD

**Issue by SeanConn15** [ap/vim-css-color#133]
I use lua for my awesomewm themes, it would be useful to use this plugin with those.
Thanks

**Comment by ap** [comment]
Lua is no longer supported and unfortunately is not likely to become supported again anytime soon. The stock Lua syntax would have to be completely rewritten first. See #65 and #70.

However you can use the old, buggy Lua support if you’re OK with the bugs. I’ve described how to do that in #70.

**Comment by SeanConn15** [comment]
My bad, I should have looked at the closed issues,  I did not anticipate any problems to arise with it. thanks.

**Comment by ap** [comment]
No worries. I might have to add an FAQ somewhere about this, it keeps coming up.
