### ISSUE TITLE
No information on how to install/use this.

### ISSUE THREAD

**Issue by FreeCap23** [ap/vim-css-color#144]
Some people are beginners to vim and have no clue how to install plugins, please be more descriptive in the README.

**Comment by ap** [comment]
There are tons of plugin management solutions and I don’t want to privilege any one of them.

Is there some curated community-maintained instructions page that I could link to?

**Comment by Saul-Dickson** [comment]
You don't have to privilege any one of them. All you have to do is include manual instructions, and the instructions to use one or two plugin managers. For example, include vim-plug. It's easy to include, hell I'll show you all you need to include in the README for it.

> Instructions for vim-plug:  
Add the following to the bottom of your `.vimrc` or `init.vim`.  
`Plug 'ap/vim-css-color'`

That's all you need to do. If I'm not mistaken, vim-plug is the most common third-party plugin manager for (Neo)VIM.

**Comment by ap** [comment]
Thanks. I have no trouble writing installer instructions.

> You don't have to privilege any one of them. All you have to do is include manual instructions [… for] one or two plugin managers.

The latter would be an example of privileging one or two plugin managers. I don’t know how that’s a way to not privilege any plugin manager.

**Comment by ap** [comment]
Of course I’m being silly. Since 8.0, Vim has had a built-in mechanism for handling packages, and obviously that is what the default instructions should target.
