### ISSUE TITLE
For the love of god add Install instructions

### ISSUE THREAD

**Issue by lefthairynut** [ap/vim-css-color#146]
I'm here wasting fucking 3 hours to work this thing done. If you don't want to "support" any plugin manager, add manual install instruction please. Fuck.

**Comment by ap** [comment]
Thanks for expressing yourself. This is already tracked in #144.

**Comment by FrenzyExists** [comment]
I was able to install it using `Plug`

`Plug 'ap/vim-css-color'`

As in `user/plugin-name`

Hope this helps!
