### ISSUE TITLE
weird inaccurate colors

### ISSUE THREAD

**Issue by stevensonmt** [ap/vim-css-color#147]
The first image is with css-color enabled, the second is without it. 

[![Screenshot-2021-02-23-21-29-08.png](https://i.postimg.cc/VLtmdSJb/Screenshot-2021-02-23-21-29-08.png)](https://postimg.cc/bsqK5wHz)
[![Screenshot-2021-02-23-21-36-14.png](https://i.postimg.cc/pVwyGM8z/Screenshot-2021-02-23-21-36-14.png)](https://postimg.cc/5jmxyGs2)
This is the color that is highlighted both fg and bg in that green color:
[![Screenshot-2021-02-23-21-44-39.png](https://i.postimg.cc/j24V4fP8/Screenshot-2021-02-23-21-44-39.png)](https://postimg.cc/q6qZkzmn)

What's going on here?

Additional info:
Interestingly vim-hexokinase displays the expected colors with the highlighting method of signcolumn or foreground but with the highlighting method of background it looks almost exactly like the css-color result above. Is it something to do with the background of my vim colorscheme?

**Comment by stevensonmt** [comment]
Error in my vimrc.

**Comment by ap** [comment]
What was the error?

**Comment by stevensonmt** [comment]
Typo of colon instead of semi-colon as pointed out by RRethy:
> Change
> 
> `let &t_8b = "\<Esc>[48:2;%lu;%lu;%lum"`
> 
> to
> 
> `let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"`
