### ISSUE TITLE
E117: Unknown function: css_color#init

### ISSUE THREAD

**Issue by MoburgLeGrand** [ap/vim-css-color#149]
I installed the plugin by cloning the git repo into my .vim/plugin folder. 
When starting vim I get a lot of `E117: Unknown function: css_color#init` error message. 
What did I do wrong  ?

**Comment by ap** [comment]
Clone it to `.vim/pack/foobar/start/vim-css-color`. (You can pick whatever directory name you what for the `foobar` and `vim-css-color` parts.) Let me know how it goes.

**Comment by MoburgLeGrand** [comment]
Everything works fine, thanks for introducing me to vim packages !

**Comment by ap** [comment]
Happy to help 🙂
