### ISSUE TITLE
Coloring for "bronze"

### ISSUE THREAD

**Issue by Aster89** [ap/vim-css-color#150]
By inspecting in Vim the HTML of StackOverflow, I've verified that `gold` and `silver` are nicely colored, whereas `bronze` is not. I guess this is a chance for improving this plugin?
![colors](https://user-images.githubusercontent.com/20521900/113853744-edc58c00-9795-11eb-90aa-a2f39bbea33b.png)

**Comment by R0LA1mRifcF8yAkk** [comment]
Sorry, but `bronze` isn't a part of the HTML color spec: https://www.w3schools.com/colors/colors_names.asp

**Comment by ap** [comment]
Nor do browsers recognise it despite that (as a non-standard extension):

<img width="333" alt="Autocomplete options offered by Chrome DevTools when filling the 'color' CSS property" src="https://user-images.githubusercontent.com/1683/114759741-d6227080-9d5e-11eb-8468-ea7b87143ad8.png">

**Comment by ap** [comment]
(The proper improvement in the case shown in your screenshot there would be that *none* of those colours should be highlighted. They are in `title` attributes, not in a `style` or `color` attribute or such where they are actually *interpreted* as colour names by the browser. CSS Color tries hard to take syntax context into account to avoid spuriously highlighting random things that look like colours. Here, unfortunately the way that the HTML syntax embeds the CSS syntax does not allow enough syntax sensitivity to avoid this.)
