### ISSUE TITLE
It would be nice to support SVG files

### ISSUE THREAD

**Issue by joeytwiddle** [ap/vim-css-color#171]
![Screenshot_20220419_153927](https://user-images.githubusercontent.com/911799/163951220-0c72c22c-7a2a-409a-9342-612deeae4416.png)

Example file:

```svg
<svg viewBox="0 0 140 140" xmlns="http://www.w3.org/2000/svg">
    <mask id="mask">
        <rect width="100%" height="100%" fill="#fff" />
        <path d="M10 0h30l50 60-50 60H10l50-60" />
    </mask>
    <path d="M130 0h-30L50 60l50 60h30L80 60" fill="#5DA5D5" mask="url(#mask)" transform="translate(5 10)" />
    <path d="M5 10h30l50 60-50 60H5l50-60" fill="#2D2E2C" />
</svg>
```

**Comment by ap** [comment]
SVG should already be supported via the support for XML in general. For me at least, it is already:

<img width="1069" alt="Screen Shot 2023-07-27 at 01 14 48" src="https://github.com/ap/vim-css-color/assets/1683/272c1283-1fa8-4bb2-b684-d99e558db939">

**Comment by ap** [comment]
SVG should already be supported via the support for XML in general. For me at least, it is already:

<img width="957" src="https://github.com/ap/vim-css-color/assets/1683/8d901bb9-7f60-4127-973b-5373cf0c0a5a">

**Comment by ap** [comment]
That said, even so, that can be improved for SVG specifically, and I have pushed that now:

<img width="958" src="https://github.com/ap/vim-css-color/assets/1683/d15ed49e-b00f-4061-9e2b-667f9bd69d28">

(Note that in this screenshot the `fill="white"` is highlighted. But RGBA is also supported.)

Share and enjoy.
