### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Doge222222** [ap/vim-css-color#181]
I cloned the repository into
~/.vim/pack/plugins/start/css-color
The plugin does not show color previews. I tried it in konsole and I also tried it in my virtual machine which uses suckless terminal and it didn’t work both times.

This is my first time using a plugin so I thought maybe I was installing it wrong so I cloned nerdtree and nerdtree worked.

Do I need to do a : command to make it start when in vim? I think I installed it correctly so maybe this is the issue.

**Comment by tehmasterer** [comment]
What type of file are you opening? The plugin does not work with all file types. Try creating a simple `.css` file and do something like: `div { color=#99ffcc }`

**Comment by Doge222222** [comment]
> What type of file are you opening? The plugin does not work with all file types. Try creating a simple `.css` file and do something like: `div { color=#99ffcc }`

I tried it in a .css file .cpp file and .java file. Does not work in any of them.

**Comment by ap** [comment]
If you open a CSS file, does `:scriptnames` say that it got loaded?

**Comment by Doge222222** [comment]
> If you open a CSS file, does the `:scriptnames` command then list it as having been loaded?

It does not appear in :scriptnames. I have ~/.vim/pack/plugins/start/css-color and ~/.vim/pack/plugins/start/css-color/after
in my run time path so I don't know why it doesn't load. I got it to work in my virtual machine so I think I messed up vim on my main machine somehow. This is something for me to fix so I'll close this issue.

**Comment by ap** [comment]
Possibly some kind of timing issue? Maybe `:help packall` / `:help packloadall` helps?

> This is something for me to fix so I'll close this issue.

No worries.
