### ISSUE TITLE
incompatible with nvim-treesitter

### ISSUE THREAD

**Issue by iHnR** [ap/vim-css-color#184]
## Description
nvim-treesitter highlighting seems to overwrite the colors provided by this plugin. I didn't get any highlighting after installing but got it to work after running `:TSDisable highlight`.

## Reproduce:
1. Install neovim >=0.8.0
2. Install [treesitter](https://github.com/nvim-treesitter/nvim-treesitter#quickstart)
3. run `:TSInstall css`, `:TSEnable highlight`

## Workaround options:
- Locally run `:TSDisable highlight`
- Add `highlight = { enable = true, disable = { "css" } }` to `init.lua`

**Comment by iHnR** [comment]
Sorry. Noticed it's a duplicate.

**Comment by ap** [comment]
Nevertheless, thank you for those workarounds! I’ve copied them to the open issue so they’ll be useful to anyone else coming here for the same problem. I’ve credited you indirectly by issue reference rather than by name in order to avoid cluttering your mentions, in case you care about that.
