### ISSUE TITLE
add support for scss files

### ISSUE THREAD

**Issue by mihaisucan** [ap/vim-css-color#35]
`vim-css-color` doesnt initialize in `scss` files when [scss-syntax](https://github.com/cakebaker/scss-syntax.vim/) is installed.

**Comment by Adityashaw** [comment]
Most **hex** values and **rgba** values are not colored in `scss` file. Do you support `scss`?

For example, the rgba here are not colored
```
body {
    position: relative;
    background: linear-gradient(to bottom, rgba(0, 47, 75, 0.5) 0%, rgba(220, 66, 37, 0.5) 100%) fixed no-repeat;
    
}
```

but it is colored when changing it to:
```
body {
    position: relative;
    //background: linear-gradient(to bottom, rgba(0, 47, 75, 0.5) 0%, rgba(220, 66, 37, 0.5) 100%) fixed no-repeat;
    
}
```

The file is saved as `style.scss` and `:set ft` shows `filetype=scss`.
