### ISSUE TITLE
How to toggle the colour highlighting on / off?

### ISSUE THREAD

**Issue by airblade** [ap/vim-css-color#43]
When I am editing a stylesheet, and I want to search for something, I find I can't see the highlighted search matches amongst all the highlighted colours.

I would love to be able to toggle the colour highlights on and off, in such a way that I can map `/` to `turn off colour highlights | now search as usual`, and update the mapping I use for `:noh` to `:noh | turn on colour highlights`.

In the meantime, thank you for a useful (and speedy) plugin.

**Comment by chemzqm** [comment]
I've got a work around to make vim-css-color works with large css files, since it's can't be toggled, I just disabled the color highlight by remove the file css.vim, and made a comand `Color` to enable the highlight, code like this:
``` VimL
command! -nargs=0 Color    :call s:HighlightColor()
function! s:HighlightColor()
  if &ft =~# '\v(css|html)'
    call css_color#init('css', 'extended', 'cssMediaBlock,cssFunction,cssDefinition,cssAttrRegion,cssComment')
  endif
  redraw
endfunction
````
I also have the line
``` VimL
syntax sync minlines=200
```
In my .vimrc to improve the highlight speed.

**Comment by ap** [comment]
Actually this was waaaaaay easier than I thought it was going to be. D’uh!

So now you can `:call css_color#toggle()` to turn it on and off in a buffer.

Sorry it took so long until my flash of the blinding obvious! :smile: Share and enjoy.

**Comment by airblade** [comment]
Thanks!
