### ISSUE TITLE
Disable on long lines

### ISSUE THREAD

**Issue by davidosomething** [ap/vim-css-color#46]
On extremely long lines, e.g. real world case `background-image: url('SUPER LONG DATA-URI');`, the `parse_css_screen` function chokes because it runs out of memory

Can you turn off exclusively on or after parts of a line that is too long (e.g. exceeds the `synmaxcol` built-in to vim's syntax highlighting)?

**Comment by ap** [comment]
Good idea.

**Comment by ap** [comment]
Well, it’s a while later, but I hope you’re still interested.

The function is called `s:parse_screen` by now. In it there is this line:

````vim
call substitute( join( getline('w0','w$'), "\n" ), b:css_color_pat, '\=s:create_syn_match()', 'g' )
````

If you change that to the following, is that enough to make vim-css-color work on files where it choked before?

````vim
call filter( range( line('w0'), line('w$') ), 'substitute( getline(v:val), b:css_color_pat, ''\=s:create_syn_match()'', ''g'' )' )
````

**Comment by ap** [comment]
> It might make the function faster too, or it might make it slower, I can’t say. I’ll have to profile to find out.

Profiling shows it to be something like 1–3%ish slower for common workloads and 5–7%ish faster for torturous workloads. That’s boils down to “no impact” as far I’m concerned, so I’ve now pushed that, at least.

**Comment by ap** [comment]
There you go. And together with #43, css-color should now work fine for files of any size.
