### ISSUE TITLE
How to enable vim-css-color for less and sass?

### ISSUE THREAD

**Issue by danbruegge** [ap/vim-css-color#49]
Hi,

how can i enable vim-css-color for less and sass?

Regards, Dan

**Comment by ap** [comment]
Support for them is included, you shouldn’t have to do anything. Does it not work?

Have you installed the plugin? (And is it this fork instead of some other version?)

What does `:set ft?` say when you open a LESS or SASS file?

**Comment by danbruegge** [comment]
Sure, i've installed the plugin. ;) With vim-plug. Yes the plugin works with .css files.

I've made a screenshot, that should explains it?!
![vim-css-color](https://cloud.githubusercontent.com/assets/1296438/7765395/cfa91320-005d-11e5-9770-6cd8e46d6ff3.png)

**Comment by ap** [comment]
Oh, right. Seems like cakebaker/scss-syntax.vim#41 is the relevant issue, i.e. you probably want to upgrade that plugin.

**Comment by danbruegge** [comment]
Ok, the plugin is not necessary for me i think. But it showed me were my problem was.
I discovered some lines in my .vimrc which i removed:

    " less with css
    autocmd BufNewFile,BufRead *.less set filetype=less.css 

    " sass with css
    autocmd BufNewFile,BufRead *.scss set filetype=scss.css
    autocmd FileType scss set iskeyword+=-

Now it is working. :) 

Thanks for the help!
