### ISSUE TITLE
Doesn't seem to render correct colours when $NVIM_TUI_ENABLE_TRUE_COLOR is set

### ISSUE THREAD

**Issue by faceleg** [ap/vim-css-color#66]

**Comment by ap** [comment]
That’s… not much to go on. Other people have said it does, so the question is what’s different in your case. Can you provide any further specifics?

**Comment by faceleg** [comment]
Yes, sorry for the lack of detail!

I'm closing this as it seems to work now ... I swear I saw it not working. If I notice the behaviour again I will re-open with more details
