### ISSUE TITLE
Reapply colors when changing background

### ISSUE THREAD

**Issue by adriaanzon** [ap/vim-css-color#71]
I currently have this autocmd in my vimrc but I thought it would make sense for this plugin to have this behavior by default:

```vim
autocmd ColorScheme * exe "runtime! after/syntax/". &ft .".vim"
```

This reapplies the colors whenever you change the color scheme or background color.

**Comment by ap** [comment]
If you remove that and check out [the `reinit` branch](/ap/vim-css-color/tree/reinit), does that work for you?

**Comment by adriaanzon** [comment]
Yep, that works fine :+1:

**Comment by ap** [comment]
Then you can now switch to back `master` and update. Enjoy. :smile:
