### ISSUE TITLE
Not seeing colors in less

### ISSUE THREAD

**Issue by bitwombat** [ap/vim-css-color#72]
I've been a happy user of your fork of vim-css-color for years, but just opened the attached less file (first time working with LESS) and am not seeing any color highlighting.  Should I be?  Am I missing a step?

I'm at 86dff1b.

[bootstrap.less.txt](https://github.com/ap/vim-css-color/files/370667/bootstrap.less.txt)

**Comment by ap** [comment]
This is what I see when I open that file:

![screenshot 2016-07-20 at 14 03 01](https://cloud.githubusercontent.com/assets/1683/16985828/52e006b2-4e83-11e6-839d-1fd2281322f0.png)

Does it not look like that for you?

**Comment by bitwombat** [comment]
It does not.

This is with an empty .vimrc and .vim (just pathgen and your plugin).

.css is fine.

**Comment by ap** [comment]
1. What does `:set ft?` say?

2. Does any `after/syntax/*.vim` file from this plugin show up in the output of `:scriptnames`?  
   Any sign of `autoload/css_color.vim`?

3. If the plugin loads correctly, does `echo keys(b:css_color_syn)` say anything or is it an error?

4. If that does not throw an error, what do you get when you put the cursor over a color name and run this command?

   ````vim
   :echo map(synstack(line("."), col(".")), "synIDattr(v:val, 'name')")
   ````

**Comment by bitwombat** [comment]
>     What does :set ft? say?

Well, there's the problem... blank.  This is stock vim at this point.  v7.4.52

It auto-detects css.  Is it supposed to auto-detect less?

If I :set ft=less  and :syntax on, still nothing. 


>   Does any after/syntax/*.vim file from this plugin show up in the output of :scriptnames?

Yes, after/syntax/less.vim

>   Any sign of autoload/css_color.vim?

Yes, verbatim.

>   If the plugin loads correctly, does echo keys(b:css_color_syn) say anything or is it an error?

Outputs ['#777', '#555', '#f0ad4e', '#333', '#222', '#5bc0de', '#000', '#5cb85c', '#eee', '#d9534f', '#337CBB']

>   If that does not throw an error, what do you get when you put the cursor on some spot that should be highlighted by the plugin (e.g. somewhere inside #5bc0de in that file) and run this command?
>   :echo map(synstack(line("."), col(".")), "synIDattr(v:val, 'name')")

Outputs []

Does that tell you anything?

**Comment by ap** [comment]
This plugin doesn’t work without a host syntax, and you haven’t got one loaded.

> Well, there's the problem... blank. This is stock vim at this point. v7.4.52
> 
> It auto-detects css. Is it supposed to auto-detect less?

My Vim package came with <https://github.com/genoma/vim-less> included. It was added some time ago, but not that long: <https://github.com/vim/vim/commits/master/runtime/syntax/less.vim>

Clicking on the first commit and looking at the tag list reveals it’s been shipped since 7.4.567.

You can upgrade Vim or install the plugin manually. Let me know whether it works after that.

**Comment by bitwombat** [comment]
Installed vim-less and now have css colours in less files!  Thanks so much Aristotle.  Sorry for bugging you for an issue that wasn't vim-css-color's problem...

**Comment by ap** [comment]
No worries. 😄
