### ISSUE TITLE
Can you put after/syntax/* into one file?

### ISSUE THREAD

**Issue by bleakwind** [ap/vim-css-color#75]
Can you put after/syntax/\* into one file?

**Comment by ap** [comment]
… why would I want to?

**Comment by ap** [comment]
(Note to self, it can be emulated with `autocmd Syntax` except that that matches on the whole `&syntax` value instead of each dot-separated part individually, and the least ugly way of dealing with that is `{*.,}foo{,.*}`.)

**Comment by ap** [comment]
I’m only closing this issue to get it out of the way, as it seems stalled; feel free to reopen any time.
