### ISSUE TITLE
shell/bash/zsh/fish support

### ISSUE THREAD

**Issue by aureooms** [ap/vim-css-color#76]
What is the easiest way to enable vim-css-color for those filetypes?

**Comment by ap** [comment]
Make a directory `~/.vim/after/syntax` and create files for the different filetypes in there. You can look at the `after/syntax/*.vim` files that ship with the plugin. If you don’t know what to name the files, open a file of the type you want to colourise and run `:set ft?`. (Regular sh/bash both use `sh`. The others are probably separate.)

**Comment by aureooms** [comment]
Where can I find a list of token names for the sh filetype?

**Comment by ap** [comment]
Sorry it’s taken me so long to get back to you.

Those are found in `syntax/sh.vim`, which Vim looks for in any of the paths in `&runtimepath`. For stuff that ships with Vim, you can just `:e $VIMRUNTIME/syntax/sh.vim`.

If you want to know which one is loaded in your particular installation, open a `sh` file and run `:scriptnames`, which will show you which files have been loaded in this Vim session, and look for the one that ends in `syntax/sh.vim`.

Another way is to open a `sh` file, put your cursor on the token you want, and run this:

```vim
:echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
```

Often there’ll be several tokens – generally you don’t want all of them, but it should be clear from the names which one you’re after.

**Comment by aureooms** [comment]
Thank you very much! I'll try this.

**Comment by Ingvix** [comment]
Did you get it to work? I'd like to get colorcodes colored in shell scripts as well.

When I installed this plugin I sort of assumed it would color pretty much every string that seems like a colorcode but it doesn't seem to do so. Is there a reason for this or is it actually hard to implement such a behavior? I'm not that experienced with the internal functionality of vim.

**Comment by aureooms** [comment]
I did not manage to get it to work.

**Comment by ap** [comment]
I’m finally actually looking into this now, and it’s no wonder you didn’t. The `sh` syntax might just be the most complicated stock syntax to support.

**Comment by ap** [comment]
I’ve now added support for a bunch of shells:

| Commit | Shell
|--------|-------
| 10e38c79d00877a46002d365eee6fde9af78d132 | sh/bash/ksh
| 21834538afc59d230fa442ca85f64ae426cf37aa | zsh
| 2c8584c0537cc23df37da4cc1e81df5dcfc8b36c | csh
| 209e26ee15d2eec5aff45bc491a0c47e5d9d0148 | tcsh

I’ll have to look into `fish`.

**Comment by ap** [comment]
Fish is now also added in 4694c6ea03a065a3f6ddbebce56797a21e8241ef.

**Comment by ap** [comment]
And with that I guess this this issue is done. Share and enjoy 🙂
