### ISSUE TITLE
Add black- and or whitelist

### ISSUE THREAD

**Issue by renstrom** [ap/vim-css-color#79]
Basically, I want a way to disable vim-css-color for certain filetypes.

**Comment by ap** [comment]
You already can.

```vim
autocmd FileType python,lua,javascript call css_color#disable()
```

I guess I need to document that part of the plugin.

**Comment by evmorov** [comment]
If you want to enable just for certain filetypes (by default the plugin is enabled for every type) and you use [vim-plug ](https://github.com/junegunn/vim-plug) you can use

```
Plug 'ap/vim-css-color', { 'for': 'css' }
```
