### ISSUE TITLE
24-bit terminal colors support

### ISSUE THREAD

**Issue by unphased** [ap/vim-css-color#86]
Sorely missing 24 bit support.

Many terms [support](https://gist.github.com/XVilka/8346728) 16 million colors.

**Comment by ap** [comment]
24 bit support was added in 7b430e85da4b7d5064627caf05045b9867f9033f.

Can’t be any more help if that’s all you tell me.

**Comment by unphased** [comment]
Yes, sorry, I posted this without doing enough research. I was testing on Vim 7.4-674 and I have since confirmed the colors work on nvim. Not sure yet if a newer Vim would support it as well. Either way you're right.

**Comment by ap** [comment]
Good. 😊  For Vim 8, `set termguicolors` to enable 24-bit terminal colours, then it should just work. If it doesn’t, gimme a holler.

**Comment by unphased** [comment]
Yep... and for earlier vims just check has('termguicolors') make it not bark on startup. 👍

**Comment by ap** [comment]
Eh, just do `silent! set termguicolors`. For guarding a single setting I’ve stopped doing the `has()` dance – too much typing, and it visually breaks up a row of `set` lines too much.

**Comment by unphased** [comment]
Oh nice trick! thanks
