### ISSUE TITLE
stylus breaking at color in .vue files 

### ISSUE THREAD

**Issue by acidjazz** [ap/vim-css-color#88]
![image](https://cloud.githubusercontent.com/assets/967369/26517542/73ee6b8a-424f-11e7-9545-3ce874ef4742.png)

if i remove/add lightblue in the code itll work, but when i scroll up and then back down it breaks again

here is the whole file for testing purposes

https://gist.github.com/acidjazz/65a27119f797471a591e2133a6dc35be

**Comment by ap** [comment]
I suspect I won’t be able to do anything about this… but let’s see. What happens if you force a redraw? (Fix it? Break it? Nothing?)

**Comment by acidjazz** [comment]
@ap a re-draw fixes it, if i scroll away from the stylus and back to it it breaks again, sometimes if i scroll away and back again it fixes it, modifying any of the stylus sometimes fixes it. its oddly behavioral. i actually tried removing vim-css-color and that doesn't seem to do much, i just can't find which vim script to blame, and it always stops at the color

**Comment by ap** [comment]
Yeah, I suspected. It’s just Vim’s highlight engine being finicky unfortunately.

My own most common experience with it is when I have a long section of POD (Perl documentation) embedded inside a Perl code file – sometimes it gets highlighted properly as POD, sometimes as just a Perl comment, and scrolling and/or redrawing will randomly fix/break it. The highlighter has some built-in checks against taking too long, I’m guessing that’s what causes it – it sometimes fires overeagerly or something like that.

Sorry I can’t offer any help.
