### ISSUE TITLE
Black/white should not reference user defined terminal colors

### ISSUE THREAD

**Issue by alexluecke** [ap/vim-css-color#93]
Neither `white` nor `black` show up as white or black. I think it currently is showing some user defined terminal color.

**Comment by ap** [comment]
It doesn’t – at least to the extent that it can.

On a 256-colour terminal, it uses colours 16 and 231 respectively, which are part of the colour cube. But the colour cube is, AFAIK, not standardised to specific RGB values, so terminals may vary a bit, and may even make the whole palette configurable. But on a 256-colour terminal there is no better option available.

On a 24bit-capable terminal, you can set `termguicolors` and then Vim will use the RGB colours from the GUI version of the colorscheme, and the colours should then be exact.

**Comment by alexluecke** [comment]
Interesting, let me dive into it a bit and see what I can find. Maybe being on iterm2 for OS X is having the impact. I will attach screenshots later as well.

**Comment by alexluecke** [comment]
Sorry I haven't gotten back to this. I will try and look at this over the coming weekend, if not I will close the issue.

**Comment by alexluecke** [comment]
Turns out my shell's base16 themes override colors 16-21 (even though it's a base "16" theme?). Closing.

**Comment by ap** [comment]
Thanks for letting me know.
