### ISSUE TITLE
Add support for i3's config file

### ISSUE THREAD

**Issue by minilud** [ap/vim-css-color#94]
Would this be possible?

Thank you for this plugin

**Comment by ap** [comment]
Share and enjoy. 😊

**Comment by C-Bouthoorn** [comment]
For some reason it doesn't seem to work on my `~/.config/i3/config` file:

![screenshot from 2018-10-12 20-18-46](https://user-images.githubusercontent.com/10348289/46886798-2c478d80-ce5c-11e8-877b-3020810ba268.png)

Its filetype is `conf`, and I enabled it via `vim-plug` with `Plug 'https://github.com/ap/vim-css-color.git'` (all other plugins work via the same method).

What am I doing wrong?

**Comment by ap** [comment]
That is not a supported filetype. Do you have an i3 syntax plugin? If you do and the filetype is still `conf` (rather than `i3` or `i3config`, depending on which plugin) then something in your setup is wrong.

**Comment by dllud** [comment]
Super! Thanks @ap !

**Comment by thiagowfx** [comment]
This is not working in vim 8.2, which ships an `i3config.vim` syntax file out-of-the-box (no external plug-ins are needed). I will send a PR to fix it.
